### ISSUE TITLE
add CS50 Libraries as dependencies

### ISSUE THREAD

**Issue by dmalan** [cs50/cli#1]
- [x] C
- [x] Java
- [x] PHP
- [x] Python

**Comment by dmalan** [comment]
- [x] C
- [ ] PHP
- [ ] Java
- [ ] Ruby
- [ ] Node.js

**Comment by kzidane** [comment]
https://github.com/cs50/cli/pull/13

C++, Node.js, and Ruby aren't ready/published yet. Will install once they are!
