### ISSUE TITLE
Module '_sqlite3' is missing in IDE

### ISSUE THREAD

**Issue by bjorn-out** [cs50/cli#105]
The Python module '_sqlite3' appears to be missing in the IDE, which causes locally run SQL checks to fail immediately:

```
Results for bjorn-out/webprogrammeren/patch-3/movies generated by check50 v3.2.0
:) SQL files exists
:( 1.sql produces correct result
    Error when executing query: No module named '_sqlite3'
```

Running the same check online does work as expected:

```
Results for bjorn-out/webprogrammeren/patch-3/movies generated by check50 v3.1.2
:) SQL files exists
:) 1.sql produces correct result
```

Attempting to import '_sqlite3' in the interactive Python shell confirms it is unavailable:
```
>>> import _sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named '_sqlite3'
```

This appears to be an issue with the installation of Python (see https://unix.stackexchange.com/questions/610875/modulenotfounderror-no-module-named-sqlite3), but I cannot really try anything out myself as the suggested solutions require root access.

**Comment by dmalan** [comment]
Apologies, my fault! Should be fixed soon!

**Comment by kzidane** [comment]
This should be fixed.
