### ISSUE TITLE
Installing persistent pip packages in IDE

### ISSUE THREAD

**Issue by bjorn-out** [cs50/cli#107]
We have been unable to install any pip packages in the IDE in a way in which they persist after a reboot. The folder ` /usr/local/lib/python3.9/site-packages` is not writable. Anything directly in `~` is removed upon reboot, such as the `~/.local/lib/python3.9` folder in which pip performs 'user installs'.

Is there a way in which to install packages in the IDE so they persist after a reboot?

**Comment by kzidane** [comment]
We reverted back the change and now `~` should persist again.
