### ISSUE TITLE
Enable cache-from and cache-to if possible

### ISSUE THREAD

**Issue by dmalan** [cs50/cli#121]
In https://github.com/cs50/cli/blob/buildx/.github/workflows/main.yml.

A la https://www.docker.com/blog/docker-v2-github-action-is-now-ga/.

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/cli/commit/a6fed81133400662e09d8a210137fb4c097b45b2](https://github.com/cs50/cli/commit/a6fed81133400662e09d8a210137fb4c097b45b2)
