### ISSUE TITLE
Should we be building aarm64 too?

### ISSUE THREAD

**Issue by dmalan** [cs50/cli#124]
Just seeing amd64 at https://hub.docker.com/r/cs50/cli/tags, so `jekyll` is still erring on M1 Macs with:

```
/usr/local/lib/ruby/gems/3.0.0/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:69:in `initialize': Function not implemented - Failed to initialize inotify (Errno::ENOSYS)
```

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/cli/commit/a6fed81133400662e09d8a210137fb4c097b45b2](https://github.com/cs50/cli/commit/a6fed81133400662e09d8a210137fb4c097b45b2)
