### ISSUE TITLE
Please consider adding an open source licence.

### ISSUE THREAD

**Issue by loryeam** [cs50/cli#128]
I just want to make a custom docker image based on cs50/cli and cs50/codespace that uses archlinux. Can't do it with current licencing i.e., no licence. Same goes for https://github.com/cs50/codespace.

**Comment by dmalan** [comment]
All set!

https://github.com/cs50/cli/commit/a48d27c773a6ef6973bf5ea75f7179442149c08d

**Comment by loryeam** [comment]
@dmalan I noticed that some of cs50 tools and (vscode) extensions are unlicenced too. Like
https://github.com/cs50/render50
https://github.com/cs50/cs50.vsix
https://github.com/cs50/phpliteadmin.vsix
https://github.com/cs50/ddb50.vsix
An open source licence on those repositories would be really appreciated. Thank you!
