### ISSUE TITLE
Disable bracketed paste as visually confusing

### ISSUE THREAD

**Issue by dmalan** [cs50/cli#147]
Per https://bugs.launchpad.net/ubuntu/+source/bash/+bug/1926256.

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/cli/commit/311efa8a212e97a53caff57f8f9eb44e5ae938f2](https://github.com/cs50/cli/commit/311efa8a212e97a53caff57f8f9eb44e5ae938f2)

**Comment by rongxin-liu** [comment]
Thanks!
