### ISSUE TITLE
Is this still necessary for libssl.so.1.1?

### ISSUE THREAD

**Issue by dmalan** [cs50/cli#162]
Just very fragile, breaks every time Ubuntu updates this library, since the old one disappears from their mirror.

https://github.com/cs50/cli/blob/e902af13ebf9ac3893fb98a2ab03ce07f790295e/Dockerfile#L199-L205

**Comment by rongxin-liu** [comment]
No need actually, removed:
https://github.com/cs50/cli/commit/de42927e5a2d74b4f3e1e0dfa72dd184d41711c7
