### ISSUE TITLE
Yarn package disappeared from Dockerfile

### ISSUE THREAD

**Issue by annikorp** [cs50/cli#169]
Hi there and good day! Just wanted to check if the yarn package still really is in the Dockerfile for cs50 Codespaces.

I keep trying to run yarn in the terminal and it keeps saying "command not found." I checked the updated cs50/cli Github Dockerfile and cross-checked it with the [Dockerfile from Docker Hub](https://hub.docker.com/r/cs50/cli/dockerfile), and it seems that the installation of yarn packages has disappeared (from the Github Dockerfile). Just wanna know if that's intentional and if yes, would there be a workaround if I need the yarn package?

Thank you so much for all that you do and I hope you have a great weekend (Or great week ahead if you see this on Monday),
Annika

**Comment by rongxin-liu** [comment]
Hi, you should be able to install `yarn` by running `npm install yarn`.

We have to keep our image as compact as possible, and since CS50 doesn't rely on yarn, we would not include it in our image.

**Comment by annikorp** [comment]
Alright. Thank you for this and for getting back to me! I really appreciate it
