### ISSUE TITLE
use `--debug=why` option for `make`

### ISSUE THREAD

**Issue by goyalyashpal** [cs50/cli#215]
hi!

[new-debug-flags]: "https://lists.gnu.org/archive/html/info-gnu/2022-10/msg00008.html#:~:text=*%20New%20debug%20option,debug%3Dprint%2Cwhy"

* the GNU make added [new flags to debug option in version 4.4](https://lists.gnu.org/archive/html/info-gnu/2022-10/msg00008.html#:~:text=*%20New%20debug%20option,debug%3Dprint%2Cwhy)
* one of them is `why` which prints info on why something is being made
* i have tried it on local system with simple projects like `cs50x/psets/5/inheritance`, the output is a one-liner and straight forward plain english of what is happening - seems perfect for beginners.
* i can totally imagine @ dmalan explaining it in lectures as such lol 😆 (hope u don't mind 😅)
   > and this line here shows the output name or more precisely target name which in this case is `inheritance`, and the reason or the file used for the target which in this case as shown is `inheritance.c`
    > 
    > all right, any questions upto this moment

output of make with this option:

```console
$ make --debug=why --silent inheritance
<builtin>: update target 'inheritance' due to: inheritance.c
```

so, this issue is just about that: including the option `--debug=why` in the cs50 configuration for make

----
* the `make --version` in the cs50 codespaces for me is shown to be `GNU Make 4.3` 
* that would need to be updated to at least `GNU Make 4.4` for this option to work, 
* otherwise currently it shows the error: `make: *** unknown debug level specification 'w'.  Stop.`

i tried running `update50` in the codespaces to see if it would resolve it, but it is always showing the following error, and i have no idea why

```console
$ update50
Failed to connect extension server on port 1337.
Please refresh the page and try again.
```

----
this issue is 
* like a continuation of https://github.com/cs50/libcs50/issues/255 , and
* inspired by investigations at https://github.com/cs50/libcs50/issues/287

**Comment by dmalan** [comment]
Thanks! We'll give this some thought!

**Comment by dmalan** [comment]
I think we're going to hold off on this for now, as we've been trying to reduce `make`'s output, save for individual errors, but we will revisit!
