### ISSUE TITLE
Clang Sanitizers not built for latest image

### ISSUE THREAD

**Issue by sgilbert-student** [cs50/cli#219]
One of my students updated her workspace this afternoon (Sunday, homework due by midnight) and found that none of the makefiles I supplied work now. The update seems to change clang from 14.0.0 to 18. Unfortunately, that breaks makefiles, which include any -fsantiize= lines. 

In the previous image, all of the santitizers were built in this folder: /usr/lib/llvm-14/lib/clang/14.0.0/lib/linux/ 

This is what make hello does (with hello.cpp)
$ make hello
/usr/bin/ld: cannot find /usr/lib/llvm-18/lib/clang/18/lib/linux/libclang_rt.ubsan_standalone-x86_64.a: No such file or directory
/usr/bin/ld: cannot find /usr/lib/llvm-18/lib/clang/18/lib/linux/libclang_rt.ubsan_standalone_cxx-x86_64.a: No such file or directory
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

I can fix this by removing all of the -fstanitize flags from CXXFLAGS
I just wish this hadn't happened on Sunday night.

**Comment by rongxin-liu** [comment]
https://github.com/cs50/codespace/commit/c4efefa86ae63958ce20549ee426f8d73745c904
