### ISSUE TITLE
scripts in /etc/profile.d are run by sh too

### ISSUE THREAD

**Issue by kzidane** [cs50/cli#54]
Scripts in `/etc/profile.d` are run by `sh` too so `bash`-only scripts shouldn't be there unless they handle `sh`? The `git-prompt.sh` is one example. Perhaps this should be placed in `~` and sourced as part of `.bashrc`?

@dmalan @crossroads1112 @glennholloway

**Comment by dmalan** [comment]
Turns out `git` already installs `/etc/bash_completion.d/git-prompt` on Ubuntu, so removing altogether per https://github.com/cs50/cli/pull/70!
