### ISSUE TITLE
 reference your own customized vim folder or .vimrc file

### ISSUE THREAD

**Issue by ehzawad** [cs50/cli#62]
It would be nice if we can add our own vimrc.local file.. How can I do that? I don't find any way.. By the way, I am newbie in docker...

**Comment by ashenm** [comment]
The use of [`--volume`](https://docs.docker.com/engine/reference/commandline/run/#add-bind-mounts-or-volumes-using-the---mount-flag) option should facilitate your need!
For instance, `docker run -itv ~/.vimrc:/home/ubuntu/.vimrc:ro cs50/cli bash --login` till it will be supported by cli50.

**Comment by dmalan** [comment]
Ah, a good idea. I've gone ahead and removed `-g` and `-s`, which were specifically for `.gitconfig` and `.ssh`, respectively, and added `-d` as a more generalized solution in version 3.0.0, which you can get with, e.g.:

```
pip3 install cli50 --upgrade
```

See https://cs50.readthedocs.io/cli50/#mount-in-container-s-home for usage!
